### ISSUE TITLE
markdown代码块不生效

### ISSUE THREAD

**Issue by raingolee** [misakar/railgun#2]
markdow代码块不生效，不知道是不是我的姿势不对，麻烦作者看看哈，谢谢

![image](https://cloud.githubusercontent.com/assets/9098953/20788053/f5e26f7e-b7e9-11e6-9deb-78f679ba9046.png)

**Comment by misakar** [comment]
谢谢反馈!  我这里是通过**缩进**控制代码块的

![2016-12-01 6 19 12](https://cloud.githubusercontent.com/assets/10671733/20790294/c5bc21ec-b7f2-11e6-9ddb-7d51dbc1827d.png)
![2016-12-01 6 20 14](https://cloud.githubusercontent.com/assets/10671733/20790310/d78f3ada-b7f2-11e6-9791-9c91d3c8c107.png)
